export async function GET() {
  const headers = new Headers({
    'Acces-Control-Allow-Origin': '*',
    'Acess-Control-Allow-Methods': 'Get, Options',
    'Access-Control-Allow-Headers': 'Content-Type',
  });

  return new Response(
    JSON.stringify({
      modelos: [
        'Audi',
        'Argo',
        'Bmw',
        'Bonnie',
        'Civic',
        'Celta',
        'Corolla',
        'Duster',
        'Doblo',
        'EcoSport',
        'Elantra',
        'Fiesta',
        'Fit',
        'Gol',
        'GrandSiena',
        'Hb20',
        'HR-V',
        'Ioniq',
        'Iluminado',
        'Jetta',
        'JacT40',
        'Kicks',
        'Ka',
        'L200Triton',
        'Logan',
        'Mobi',
        'Montana',
        'NissanLeaf',
        'Nivus',
        'Onix',
        'Opala',
        'Polo',
        'Palio',
        'Prisma',
        'Q3',
        'Q5',
        'Renegade',
        'Ranger',
        'Spin',
        'Sandero',
        'Tracker',
        'T-Cross',
        'Up!',
        'Uno',
        'Virtus',
        'Versa',
        'Wrangler',
        'WagonR',
        'X3',
        'X5',
        'X8',
        'Yaris',
        'Yeti',
        'Zafira',
        'Zoe',
      ],
    }),
    {
      headers,
    },
  );
}
